[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"


[project]
name = "axira"
version = "1.1.0"
description = "Axira is a Python engine for creating precise programmed mathematical animations."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "Pillow>=10.0",
    "imageio>=2.34",
    "imageio-ffmpeg>=0.5",
    "svgpathtools>=1.6",
]


[project.scripts]
axira = "axira.cli:main"


[tool.setuptools.packages.find]
where = ["src"]