[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "axira"
version = "0.1.0"
description = "Axira is a Python library used to create precise, programmed mathematical animations"
requires-python = ">=3.10"
dependencies = [
    "imageio>=2.31",
    "imageio-ffmpeg>=0.4.9",
    "Pillow>=10.0",
    "svgpathtools>=1.6",
]

[project.scripts]
axira = "axira.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
